-- SOMENTE DEMONSTRACAO ISOLADA. Nunca aplicar em uma agenda real.
INSERT OR IGNORE INTO business_settings (id,timezone,cancellation_limit_hours,minimum_notice_minutes,booking_horizon_days,slot_step_minutes,default_buffer_minutes,policy_version,updated_at) VALUES ('main','America/Sao_Paulo',4,60,30,30,0,'demo-v1',datetime('now'));
INSERT OR IGNORE INTO categories (id,name,slug,active,display_order) VALUES ('cat-cortes','Cortes','cortes',1,1);
INSERT OR IGNORE INTO categories (id,name,slug,active,display_order) VALUES ('cat-infantil','Infantil','infantil',1,2);
INSERT OR IGNORE INTO categories (id,name,slug,active,display_order) VALUES ('cat-demo','Demonstração','demonstracao',1,3);
INSERT OR IGNORE INTO professionals (id,name,active,display_order,created_at,updated_at) VALUES ('pro-ismael','Ismael',1,1,'2026-09-22T00:00:00.000Z','2026-09-22T00:00:00.000Z');
INSERT OR IGNORE INTO professionals (id,name,active,display_order,created_at,updated_at) VALUES ('pro-leonardo','Leonardo',1,2,'2026-09-22T00:00:00.000Z','2026-09-22T00:00:00.000Z');
INSERT OR IGNORE INTO services (id,category_id,name,description,price_cents,duration_minutes,source,active,display_order,created_at,updated_at) VALUES ('srv-corte','cat-cortes','Corte','Corte masculino. Duração demonstrativa até validação.',4000,45,'observed',1,1,'2026-09-22T00:00:00.000Z','2026-09-22T00:00:00.000Z');
INSERT OR IGNORE INTO professional_services (professional_id,service_id) VALUES ('pro-ismael','srv-corte');
INSERT OR IGNORE INTO services (id,category_id,name,description,price_cents,duration_minutes,source,active,display_order,created_at,updated_at) VALUES ('srv-corte-infantil','cat-infantil','Corte infantil (3 a 8 anos)','Atendimento infantil. Duração demonstrativa até validação.',4000,40,'observed',1,2,'2026-09-22T00:00:00.000Z','2026-09-22T00:00:00.000Z');
INSERT OR IGNORE INTO professional_services (professional_id,service_id) VALUES ('pro-ismael','srv-corte-infantil');
INSERT OR IGNORE INTO services (id,category_id,name,description,price_cents,duration_minutes,source,active,display_order,created_at,updated_at) VALUES ('srv-barba-demo','cat-demo','Barba — exemplo da demonstração','Serviço sintético para testar a agenda; não é oferta oficial.',3500,30,'demo',1,3,'2026-09-22T00:00:00.000Z','2026-09-22T00:00:00.000Z');
INSERT OR IGNORE INTO professional_services (professional_id,service_id) VALUES ('pro-ismael','srv-barba-demo');
INSERT OR IGNORE INTO professional_services (professional_id,service_id) VALUES ('pro-leonardo','srv-barba-demo');
INSERT OR IGNORE INTO services (id,category_id,name,description,price_cents,duration_minutes,source,active,display_order,created_at,updated_at) VALUES ('srv-acabamento-demo','cat-demo','Acabamento — exemplo da demonstração','Serviço sintético para testar combinações; não é oferta oficial.',2000,20,'demo',1,4,'2026-09-22T00:00:00.000Z','2026-09-22T00:00:00.000Z');
INSERT OR IGNORE INTO professional_services (professional_id,service_id) VALUES ('pro-ismael','srv-acabamento-demo');
INSERT OR IGNORE INTO professional_services (professional_id,service_id) VALUES ('pro-leonardo','srv-acabamento-demo');
INSERT OR IGNORE INTO unit_schedules (weekday,start_minute,end_minute) VALUES (1,540,1080);
INSERT OR IGNORE INTO weekly_schedules (id,professional_id,weekday,start_minute,end_minute,break_start_minute,break_end_minute) VALUES ('sch-pro-ismael-1','pro-ismael',1,540,1080,720,780);
INSERT OR IGNORE INTO weekly_schedules (id,professional_id,weekday,start_minute,end_minute,break_start_minute,break_end_minute) VALUES ('sch-pro-leonardo-1','pro-leonardo',1,540,1080,720,780);
INSERT OR IGNORE INTO unit_schedules (weekday,start_minute,end_minute) VALUES (2,540,1080);
INSERT OR IGNORE INTO weekly_schedules (id,professional_id,weekday,start_minute,end_minute,break_start_minute,break_end_minute) VALUES ('sch-pro-ismael-2','pro-ismael',2,540,1080,720,780);
INSERT OR IGNORE INTO weekly_schedules (id,professional_id,weekday,start_minute,end_minute,break_start_minute,break_end_minute) VALUES ('sch-pro-leonardo-2','pro-leonardo',2,540,1080,720,780);
INSERT OR IGNORE INTO unit_schedules (weekday,start_minute,end_minute) VALUES (3,540,1080);
INSERT OR IGNORE INTO weekly_schedules (id,professional_id,weekday,start_minute,end_minute,break_start_minute,break_end_minute) VALUES ('sch-pro-ismael-3','pro-ismael',3,540,1080,720,780);
INSERT OR IGNORE INTO weekly_schedules (id,professional_id,weekday,start_minute,end_minute,break_start_minute,break_end_minute) VALUES ('sch-pro-leonardo-3','pro-leonardo',3,540,1080,720,780);
INSERT OR IGNORE INTO unit_schedules (weekday,start_minute,end_minute) VALUES (4,540,1080);
INSERT OR IGNORE INTO weekly_schedules (id,professional_id,weekday,start_minute,end_minute,break_start_minute,break_end_minute) VALUES ('sch-pro-ismael-4','pro-ismael',4,540,1080,720,780);
INSERT OR IGNORE INTO weekly_schedules (id,professional_id,weekday,start_minute,end_minute,break_start_minute,break_end_minute) VALUES ('sch-pro-leonardo-4','pro-leonardo',4,540,1080,720,780);
INSERT OR IGNORE INTO unit_schedules (weekday,start_minute,end_minute) VALUES (5,540,1080);
INSERT OR IGNORE INTO weekly_schedules (id,professional_id,weekday,start_minute,end_minute,break_start_minute,break_end_minute) VALUES ('sch-pro-ismael-5','pro-ismael',5,540,1080,720,780);
INSERT OR IGNORE INTO weekly_schedules (id,professional_id,weekday,start_minute,end_minute,break_start_minute,break_end_minute) VALUES ('sch-pro-leonardo-5','pro-leonardo',5,540,1080,720,780);
INSERT OR IGNORE INTO unit_schedules (weekday,start_minute,end_minute) VALUES (6,540,1080);
INSERT OR IGNORE INTO weekly_schedules (id,professional_id,weekday,start_minute,end_minute,break_start_minute,break_end_minute) VALUES ('sch-pro-ismael-6','pro-ismael',6,540,1080,720,780);
INSERT OR IGNORE INTO weekly_schedules (id,professional_id,weekday,start_minute,end_minute,break_start_minute,break_end_minute) VALUES ('sch-pro-leonardo-6','pro-leonardo',6,540,1080,720,780);
